baseurl:        ""
destination:    "docs/"
email:          "info@lexgera.it"
highlighter:     none
ragione-sociale: "Lexgera ..."
telefono:       "+39 "
cf_pi:          "cv/p.iva"
url:            "https://lexgera.it"
pec:            "lexgera@legalmail.it"
sede:           "Via ... - ROMA"

sass:
    style: compressed

exclude: [
  'bin'
, 'conf'
, 'CHANGELOG'
, 'TODO'
, 'VERSION'
, 'README.md'
]

webrick:
  headers:
    X-Frame-Options: SAMEORIGIN
    X-Content-Type-Options: "nosniff"
    # Content-Security-Policy: default-src 'self' igiornidelciclo.it *.igiornidelciclo.it
    X-XSS-Protection: "1; mode=block"
