baseurl:        ""
destination:    "docs/"
fqdn:           "lexgera.it"
highlighter:     none
url:            "https://lexgera.it"

sass:
    style: compressed

exclude: [
  'bin'
, 'conf'
, 'CHANGELOG'
, 'TODO'
, 'VERSION'
, 'README.md'
]

webrick:
  headers:
    X-Frame-Options: SAMEORIGIN
    X-Content-Type-Options: "nosniff"
    # Content-Security-Policy: default-src 'self' igiornidelciclo.it *.igiornidelciclo.it
    X-XSS-Protection: "1; mode=block"
